import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { mkdtemp, rm, readFile, mkdir, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

// Shared state for the mock — set in beforeEach, read by the mock lazily
let tempDir: string;

vi.mock('../src/config.js', () => ({
  loadConfig: () => ({
    wirenest: { url: 'http://localhost:5180' },
    wiki: { get basePath() { return tempDir; } },
  }),
}));

// Import after mock
const { registerWikiTools } = await import('../src/connectors/wiki.js');

/** Create a fresh temp wiki directory with standard structure. */
async function setupWikiDir(): Promise<string> {
  const dir = await mkdtemp(join(tmpdir(), 'wirenest-wiki-test-'));
  await mkdir(join(dir, 'pages'), { recursive: true });
  await writeFile(join(dir, 'index.md'), `# WireNest Wiki — Index

> Content catalog for the knowledge base. Regenerated between @auto-index sentinels.

## Full Catalog

<!-- @auto-index:start -->
<!-- regenerated by wiki.write -->
<!-- @auto-index:end -->
`);
  await writeFile(join(dir, 'log.md'), `# WireNest Wiki — Log

> Chronological record of wiki operations. Append-only.

## [2026-04-08] init | Wiki initialized
- Created wiki structure (schema, index, log)
`);
  return dir;
}

/** Call an MCP tool by name via internal handler map. */
async function callTool(server: McpServer, name: string, args: Record<string, unknown> = {}) {
  const tools = (server as any)._registeredTools as Record<string, { handler: Function }>;
  const tool = tools[name];
  if (!tool) throw new Error(`Tool "${name}" not registered. Available: ${Object.keys(tools).join(', ')}`);
  const extra = {
    signal: new AbortController().signal,
    requestId: 'test',
    sendNotification: async () => {},
    sendRequest: async () => ({}),
  };
  return tool.handler(args, extra);
}

describe('wiki tools', () => {
  let server: McpServer;

  beforeEach(async () => {
    tempDir = await setupWikiDir();
    server = new McpServer({ name: 'test', version: '0.0.1' });
    registerWikiTools(server);
  });

  afterEach(async () => {
    await rm(tempDir, { recursive: true, force: true });
  });

  describe('wiki.list', () => {
    it('reports no pages when wiki is empty', async () => {
      const result = await callTool(server, 'wiki.list');
      expect(result.isError).toBeFalsy();
      expect(result.content[0].text).toContain('No wiki pages yet');
    });

    it('lists pages after one is created', async () => {
      await writeFile(join(tempDir, 'pages', 'test-page.md'), `---
title: Test Page
type: concept
tags: [testing]
created: 2026-04-11
updated: 2026-04-11
---

# Test Page

Some content.
`);
      const result = await callTool(server, 'wiki.list');
      expect(result.content[0].text).toContain('1 wiki page(s)');
      expect(result.content[0].text).toContain('Test Page');
      expect(result.content[0].text).toContain('concept');
    });
  });

  describe('wiki.read', () => {
    it('reads an existing page', async () => {
      const pageContent = `---
title: DNS Resolution
type: concept
tags: [dns, networking]
created: 2026-04-11
updated: 2026-04-11
---

# DNS Resolution

Pi-hole handles all DNS.
`;
      await writeFile(join(tempDir, 'pages', 'dns-resolution.md'), pageContent);

      const result = await callTool(server, 'wiki.read', { path: 'pages/dns-resolution.md' });
      expect(result.isError).toBeFalsy();
      expect(result.content[0].text).toBe(pageContent);
    });

    it('returns error for missing page', async () => {
      const result = await callTool(server, 'wiki.read', { path: 'pages/nonexistent.md' });
      expect(result.isError).toBe(true);
      expect(result.content[0].text).toContain('not found');
    });

    it('rejects path traversal', async () => {
      const result = await callTool(server, 'wiki.read', { path: '../../etc/passwd' });
      expect(result.isError).toBe(true);
      expect(result.content[0].text).toContain('path traversal');
    });
  });

  describe('wiki.write', () => {
    const testContent = `---
title: VLAN Design
type: decision
tags: [networking, vlans]
created: 2026-04-11
updated: 2026-04-11
---

# VLAN Design

Management on VLAN 10, servers on VLAN 30.
`;

    it('creates a new page and updates index + log', async () => {
      const result = await callTool(server, 'wiki.write', {
        path: 'pages/vlan-design.md',
        content: testContent,
        summary: 'VLAN segmentation rationale',
        reason: 'documenting network design choices',
      });

      expect(result.isError).toBeFalsy();
      expect(result.content[0].text).toContain('Created');

      // Page written correctly
      const page = await readFile(join(tempDir, 'pages', 'vlan-design.md'), 'utf-8');
      expect(page).toBe(testContent);

      // Index regenerated between sentinels — page now listed under its type.
      const index = await readFile(join(tempDir, 'index.md'), 'utf-8');
      expect(index).toContain('VLAN Design');
      expect(index).toContain('pages/vlan-design.md');
      expect(index).toContain('### Decisions');
      // Summary lives in log.md now — auto-index is just the catalog.

      // Log appended (summary + reason land here)
      const log = await readFile(join(tempDir, 'log.md'), 'utf-8');
      expect(log).toContain('create');
      expect(log).toContain('VLAN Design');
      expect(log).toContain('VLAN segmentation rationale');
    });

    it('updates an existing page without duplicating index entry', async () => {
      await callTool(server, 'wiki.write', {
        path: 'pages/vlan-design.md',
        content: testContent,
        summary: 'Initial VLAN rationale',
        reason: 'initial write',
      });

      const updatedContent = testContent.replace('Management on VLAN 10', 'Management on VLAN 5');
      const result = await callTool(server, 'wiki.write', {
        path: 'pages/vlan-design.md',
        content: updatedContent,
        summary: 'Updated VLAN numbering',
        reason: 'renumbering VLANs',
      });

      expect(result.content[0].text).toContain('Updated');

      // Index has exactly one entry
      const index = await readFile(join(tempDir, 'index.md'), 'utf-8');
      const matches = index.match(/vlan-design\.md/g);
      expect(matches).toHaveLength(1);

      // Log has both operations
      const log = await readFile(join(tempDir, 'log.md'), 'utf-8');
      expect(log).toContain('create');
      expect(log).toContain('update');
    });

    it('rejects writes outside pages/', async () => {
      const result = await callTool(server, 'wiki.write', {
        path: 'index.md',
        content: '# hacked',
        summary: 'overwrite index',
        reason: 'test',
      });
      expect(result.isError).toBe(true);
      expect(result.content[0].text).toContain('pages/');
    });

    it('rejects content without frontmatter', async () => {
      const result = await callTool(server, 'wiki.write', {
        path: 'pages/bad.md',
        content: '# No frontmatter here',
        summary: 'missing frontmatter',
        reason: 'test',
      });
      expect(result.isError).toBe(true);
      expect(result.content[0].text).toContain('frontmatter');
    });

    it('creates subdirectories as needed', async () => {
      const result = await callTool(server, 'wiki.write', {
        path: 'pages/networking/dns.md',
        content: testContent,
        summary: 'DNS deep dive',
        reason: 'documenting DNS',
      });
      expect(result.isError).toBeFalsy();

      const page = await readFile(join(tempDir, 'pages', 'networking', 'dns.md'), 'utf-8');
      expect(page).toBe(testContent);
    });
  });

  describe('wiki.search', () => {
    beforeEach(async () => {
      await writeFile(join(tempDir, 'pages', 'dns-resolution.md'), `---
title: DNS Resolution
type: concept
tags: [dns, networking, pihole]
created: 2026-04-11
updated: 2026-04-11
---

# DNS Resolution

Pi-hole handles all DNS queries on the network.
pfSense forwards upstream to Cloudflare.
`);
      await writeFile(join(tempDir, 'pages', 'vlan-design.md'), `---
title: VLAN Design
type: decision
tags: [networking, vlans]
created: 2026-04-11
updated: 2026-04-11
---

# VLAN Design

Management on VLAN 10, servers on VLAN 30.
`);
    });

    it('finds pages by body content', async () => {
      const result = await callTool(server, 'wiki.search', { query: 'Cloudflare' });
      expect(result.content[0].text).toContain('1 result');
      expect(result.content[0].text).toContain('DNS Resolution');
    });

    it('finds pages by title', async () => {
      const result = await callTool(server, 'wiki.search', { query: 'VLAN' });
      expect(result.content[0].text).toContain('VLAN Design');
    });

    it('finds pages by tag', async () => {
      const result = await callTool(server, 'wiki.search', { query: 'pihole' });
      expect(result.content[0].text).toContain('DNS Resolution');
    });

    it('is case-insensitive', async () => {
      const result = await callTool(server, 'wiki.search', { query: 'dns' });
      expect(result.content[0].text).toContain('DNS Resolution');
    });

    it('returns no results for unmatched query', async () => {
      const result = await callTool(server, 'wiki.search', { query: 'kubernetes' });
      expect(result.content[0].text).toContain('No wiki pages match');
    });

    it('returns empty message when wiki has no pages', async () => {
      await rm(join(tempDir, 'pages'), { recursive: true, force: true });
      await mkdir(join(tempDir, 'pages'));

      const result = await callTool(server, 'wiki.search', { query: 'anything' });
      expect(result.content[0].text).toContain('No wiki pages to search');
    });
  });

  describe('wiki.create_page', () => {
    async function seedTemplates() {
      await mkdir(join(tempDir, 'templates'), { recursive: true });
      await writeFile(
        join(tempDir, 'templates', 'device.md'),
        '---\ntitle: {{title}}\nslug: {{slug}}\ntype: device\ncreated: {{today}}\n{{entity_ref}}---\n\n# {{title}}\n',
      );
      await writeFile(
        join(tempDir, 'templates', 'vlan.md'),
        '---\ntitle: {{title}}\nslug: {{slug}}\ntype: vlan\ncreated: {{today}}\n{{entity_ref}}---\n\n# {{title}}\n\nSubnet: <!-- @sot:vlan/{{entity_id}}.subnet -->\n',
      );
    }

    beforeEach(seedTemplates);

    it('stamps a template with title/slug/today', async () => {
      const result = await callTool(server, 'wiki.create_page', {
        type: 'device',
        slug: 'pve01',
        title: 'pve01',
      });
      expect(result.isError).toBeFalsy();
      expect(result.content[0].text).toContain('Created device page');

      const page = await readFile(join(tempDir, 'pages', 'devices', 'pve01.md'), 'utf-8');
      expect(page).toContain('title: pve01');
      expect(page).toContain('slug: pve01');
      expect(page).toContain('type: device');
      expect(page).toMatch(/created: \d{4}-\d{2}-\d{2}/);
    });

    it('emits entity_ref when provided and substitutes {{entity_id}}', async () => {
      const result = await callTool(server, 'wiki.create_page', {
        type: 'vlan',
        slug: 'vlan-20',
        title: 'VLAN 20 — Trusted',
        entity_ref: { type: 'vlan', id: 20 },
      });
      expect(result.isError).toBeFalsy();

      const page = await readFile(join(tempDir, 'pages', 'vlans', 'vlan-20.md'), 'utf-8');
      expect(page).toContain('entity_ref:');
      expect(page).toContain('type: vlan');
      expect(page).toContain('id: 20');
      expect(page).toContain('<!-- @sot:vlan/20.subnet -->');
    });

    it('writes to the correct type subdirectory', async () => {
      await callTool(server, 'wiki.create_page', {
        type: 'device',
        slug: 'test-dev',
        title: 'Test',
      });
      const page = await readFile(join(tempDir, 'pages', 'devices', 'test-dev.md'), 'utf-8');
      expect(page).toContain('title: Test');
    });

    it('refuses to clobber an existing page', async () => {
      await callTool(server, 'wiki.create_page', {
        type: 'device',
        slug: 'dup',
        title: 'First',
      });
      const result = await callTool(server, 'wiki.create_page', {
        type: 'device',
        slug: 'dup',
        title: 'Second',
      });
      expect(result.isError).toBe(true);
      expect(result.content[0].text).toContain('already exists');
    });

    it('sanitizes the slug', async () => {
      const result = await callTool(server, 'wiki.create_page', {
        type: 'device',
        slug: 'My Device!',
        title: 'My Device',
      });
      expect(result.isError).toBeFalsy();
      const page = await readFile(join(tempDir, 'pages', 'devices', 'my-device.md'), 'utf-8');
      expect(page).toContain('slug: my-device');
    });

    it('appends a log.md entry', async () => {
      await callTool(server, 'wiki.create_page', {
        type: 'device',
        slug: 'logged',
        title: 'Logged Device',
      });
      const log = await readFile(join(tempDir, 'log.md'), 'utf-8');
      expect(log).toContain('create');
      expect(log).toContain('Logged Device');
    });

    it('errors when the template file is missing', async () => {
      await rm(join(tempDir, 'templates', 'device.md'));
      const result = await callTool(server, 'wiki.create_page', {
        type: 'device',
        slug: 'x',
        title: 'X',
      });
      expect(result.isError).toBe(true);
      expect(result.content[0].text).toContain('template not found');
    });
  });
});
